# nginx/nginx.conf

events { 
    worker_connections 1024; 
}

http {
    # This block defines our backend servers
    upstream flask_apps {
        # By default, Nginx does 50/50 Round Robin load balancing
        server app-blue:5000;
        server app-green:5000;
    }

    # This block tells Nginx to listen on port 80 (standard HTTP)
    server {
        listen 80;

        location / {
            # Forward all traffic to the upstream block defined above
            proxy_pass http://flask_apps;
            
            # Pass along some headers so the app knows who is calling
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
